name: borigarn
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  mask_text_input_formatter: ^2.4.0
  flutter_svg: ^2.0.10+1
  flutter_countdown_timer: ^4.1.0
  http: ^1.1.0
  crypto: ^3.0.2
  nanoid: ^1.0.0
  device_info_plus: ^9.0.2
  get: ^4.6.5
  image_picker: ^1.0.7
  shared_preferences: ^2.0.18
  image_cropper: ^5.0.0
  dio: ^5.0.2
  http_parser: ^4.0.2
  cached_network_image: ^3.2.3

  gap: ^3.0.0
  loading_indicator: ^3.1.0
  intl: ^0.18.0
  ensure_visible_when_focused: ^1.1.1
  flutter_keyboard_visibility: ^5.4.0
  sms_autofill: ^2.3.0
  carousel_slider: ^4.2.1

  fluttertoast: ^8.2.1
  flutter_cache_manager: ^3.3.0
  video_player: ^2.6.1
  shimmer: ^3.0.0
  video_thumbnail: ^0.5.3
  path_provider: ^2.0.14
  visibility_detector: ^0.4.0+2
  photo_view: ^0.14.0
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.1.11
  flutter_markdown: ^0.6.14
  quiver: ^3.2.1
  flutter_time_picker_spinner: ^2.0.0
  dotted_border: ^2.0.0+3
  widgets_to_image: ^0.0.2
  image_gallery_saver: ^2.0.3
  screenshot: ^2.1.0
  page_transition: ^2.0.9
  uni_links: ^0.5.1

  timezone: ^0.9.2
  riverpod_annotation: ^2.1.1
  hidable: ^1.0.4
  freezed_annotation: ^2.4.1
  gradient_widgets: ^0.6.0
  hooks_riverpod: ^2.3.6
  permission_handler: ^11.0.1

  sliver_tools: ^0.2.10
  collection: ^1.17.1
  percent_indicator: ^4.2.3
  flutter_native_splash: ^2.3.1

  #update new architecture
  easy_localization: ^3.0.2
  dartz: ^0.10.1
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  flutter_rating_bar: ^4.0.1
  adaptive_dialog: ^1.9.0
  flutter_hooks: ^0.20.0
  auto_size_text: ^3.0.0
  go_router: ^12.0.0
  blur: ^3.1.0
  font_awesome_flutter: ^10.5.0
  flutter_easyloading: ^3.0.5
  easy_debounce: ^2.0.3
  material_symbols_icons: ^4.2668.0
  package_info_plus: ^4.1.0
  dropdown_button2: ^2.3.9
  flutter_staggered_grid_view: ^0.7.0
  scan: ^1.6.0
  webview_flutter: ^4.7.0
  simple_progress_indicators: ^0.2.0
  http_mock_adapter: ^0.4.4
  flutter_rounded_date_picker: ^3.0.4
  basic_utils: ^5.7.0
  material_design_icons_flutter: 7.0.7296
  flutter_screenutil: ^5.9.0
  readmore: ^2.2.0
  google_sign_in: ^6.2.1
  flutter_social_button: ^1.1.4+1
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  google_maps_flutter: ^2.6.0
  ionicons: ^0.2.2
  map_picker: ^0.0.3
  geocoding: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html: ^0.14.11
  flutter_inappwebview: ^6.0.0
  #  appcenter: ^0.2.1
  #  appcenter_analytics: ^0.2.1
  #  appcenter_crashes: ^0.2.1
  # connectivity_plus: ^3.0.2
  # rename: ^2.0.1



dev_dependencies:
  flutter_flavorizr:
  flutter_launcher_icons: "^0.13.1"
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  #  integration_test:
  #    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  mocktail: ^1.0.1
  custom_lint:
  riverpod_lint: ^2.3.2
  freezed: ^2.4.1
  # flutter_native_splash: ^2.3.1
  json_serializable: ^6.7.1


  # change_app_package_name: ^1.1.0

#patrol:
#  app_name: My Pinmall
#  flavor: development
#  android:
#    package_name: com.mypinmall.beta
#  ios:
#    bundle_id: com.mypinmall.beta
#    app_name: My Pinmall

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
  #    rive: true
  #    lottie: true
  assets:
    enabled: true
    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case
      # Assets.images_chip
      # style: snake-case
      # Assets.images.chip (default style)
      style: dot-delimiter



flutter_launcher_icons:
  #  android: "launcher_icon"
  ios: true
  android: true
  image_path: "assets/icons/icon_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true



flutter_native_splash:
  web: false
  image: assets/splash_screen.png
  color: "#F5F8F9"

  android_12:
    image: assets/splash_screen.png
    color: "#07BEF2"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/
    - assets/profile/
    - assets/category/
    - assets/status/
    - assets/booking/
    - assets/local/


targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true,
          generic_argument_factories: true
